all:
  children:
    svi:
      hosts:
        svi-server:
          ansible_host: 20.91.255.221
          ansible_user: ansiadmin
          ansible_ssh_private_key_file: inventory/.ssh/id_rsa
          ansible_python_interpreter: /usr/bin/python3
    qa:
      hosts:
        qa-server:
          ansible_host: 20.91.255.191
          ansible_user: ansiadmin
          ansible_ssh_private_key_file: inventory/.ssh/id_rsa
          ansible_python_interpreter: /usr/bin/python3
    prod:
      hosts:
        prod-server:
          ansible_host: 20.91.255.71
          ansible_user: ansiadmin
          ansible_ssh_private_key_file: inventory/.ssh/id_rsa
          ansible_python_interpreter: /usr/bin/python3
