#SPDX-License-Identifier: MIT-0
---
# handlers file for activemq_setup
- name: Restart ActiveMQ
  ansible.builtin.systemd:
    name: activemq
    state: restarted
  listen: "restart activemq"

- name: Check ActiveMQ Status
  ansible.builtin.command: systemctl status activemq
  register: activemq_status
  changed_when: false
  ignore_errors: true

- name: Show ActiveMQ Status
  ansible.builtin.debug:
    msg: "{{ activemq_status.stdout_lines }}"
