#SPDX-License-Identifier: MIT-0
---
# tasks file for activemq_setup
- name: Create activemq group
  ansible.builtin.group:
    name: activemq
    state: present

- name: Create activemq user
  ansible.builtin.user:
    name: activemq
    group: activemq
    home: /opt/activemq
    shell: /bin/bash
    system: true

- name: Install System Requirements (Java 21 JDK, unzip, wget)
  ansible.builtin.apt:
    name:
      - openjdk-21-jdk
      - unzip
      - wget
    state: present
    update_cache: true
  when: ansible_os_family == "Debian"

- name: Install System Requirements (Java 21 JDK, unzip, wget - RedHat)
  ansible.builtin.yum:
    name:
      - java-21-openjdk
      - unzip
      - wget
    state: present
    update_cache: true
  when: ansible_os_family == "RedHat"

- name: Download ActiveMQ
  ansible.builtin.get_url:
    url: "https://downloads.apache.org/activemq/5.19.0/apache-activemq-5.19.0-bin.tar.gz"
    dest: "/tmp/apache-activemq.tar.gz"
  when: not ansible_check_mode

- name: Extract ActiveMQ
  ansible.builtin.unarchive:
    src: "/tmp/apache-activemq.tar.gz"
    dest: "/opt/"
    remote_src: true
  when: not ansible_check_mode

- name: Set ownership and permissions
  ansible.builtin.file:
    path: "/opt/apache-activemq-5.19.0"
    owner: activemq
    group: activemq
    recurse: true
    mode: "0755"

- name: Delete symlink dir if existing
  ansible.builtin.file:
    path: "/opt/activemq"
    state: absent

- name: Set symlink
  ansible.builtin.file:
    src: "/opt/apache-activemq-5.19.0"
    dest: "/opt/activemq"
    state: link

- name: Deploy ActiveMQ configuration
  ansible.builtin.template:
    src: activemq.xml.j2
    dest: "/opt/activemq/conf/activemq.xml"
    owner: activemq
    group: activemq
    mode: "0755"
  notify: Restart ActiveMQ

- name: Create ActiveMQ systemd service
  ansible.builtin.template:
    src: activemq.service.j2
    dest: "/etc/systemd/system/activemq.service"
    owner: root
    group: root
    mode: "0755"
  notify: Restart ActiveMQ

- name: Start and Enable ActiveMQ
  ansible.builtin.systemd:
    name: activemq
    state: started
    enabled: true
